*----------------------------------------------------------------------*
*   INCLUDE INCLKONS                                                   *
*
* Konstanten
*
DATA: CHAR_A(1) TYPE C VALUE 'A',
      CHAR_B(1) TYPE C VALUE 'B',
      CHAR_C(1) TYPE C VALUE 'C',
      CHAR_D(1) TYPE C VALUE 'D',
      CHAR_E(1) TYPE C VALUE 'E',
      CHAR_F(1) TYPE C VALUE 'F',
      CHAR_G(1) TYPE C VALUE 'G',
      CHAR_H(1) TYPE C VALUE 'H',
      CHAR_I(1) TYPE C VALUE 'I',
      CHAR_J(1) TYPE C VALUE 'J',
      CHAR_K(1) TYPE C VALUE 'K',
      CHAR_L(1) TYPE C VALUE 'L',
      CHAR_M(1) TYPE C VALUE 'M',
      CHAR_N(1) TYPE C VALUE 'N',
      CHAR_O(1) TYPE C VALUE 'O',
      CHAR_P(1) TYPE C VALUE 'P',
      CHAR_Q(1) TYPE C VALUE 'Q',
      CHAR_R(1) TYPE C VALUE 'R',
      CHAR_S(1) TYPE C VALUE 'S',
      CHAR_T(1) TYPE C VALUE 'T',
      CHAR_U(1) TYPE C VALUE 'U',
      CHAR_V(1) TYPE C VALUE 'V',
      CHAR_W(1) TYPE C VALUE 'W',
      CHAR_X(1) TYPE C VALUE 'X',
      CHAR_Y(1) TYPE C VALUE 'Y',
      CHAR_Z(1) TYPE C VALUE 'Z',
      CHAR__(1) TYPE C VALUE '_',
      CHAR_*(1) TYPE C VALUE '*',
      CHAR_?(1) TYPE C VALUE '?',
      CHAR_0(1) TYPE C VALUE '0',
      CHAR_1(1) TYPE C VALUE '1',
      CHAR_2(1) TYPE C VALUE '2',
      CHAR_3(1) TYPE C VALUE '3',
      CHAR_4(1) TYPE C VALUE '4',
      CHAR_5(1) TYPE C VALUE '5',
      CHAR_6(1) TYPE C VALUE '6',
      CHAR_7(1) TYPE C VALUE '7',
      CHAR_8(1) TYPE C VALUE '8',
      CHAR_9(1) TYPE C VALUE '9'.
