*&---------------------------------------------------------------------*
*& Include ZPG_FIE002_TOP
*&
*&---------------------------------------------------------------------*
REPORT zpg_fie001.
TABLES: sscrfields.
**---------------------------------------------------------------------*
TYPES: BEGIN OF  ty_upload,
         stt               TYPE string,
         doc_date          TYPE string,
         pstng_date        TYPE string,
         header_txt        TYPE string,
         mau_hd            TYPE string,
         ref_doc_no        TYPE string,
         doc_type          TYPE string,
         comp_code         TYPE string,
         currency          TYPE string,
         trans_date        TYPE string,
         de_cre_ind1       TYPE string,
         gl_account        TYPE string,
*         CUSTOMER    TYPE STRING,
*         VENDOR_NO   TYPE STRING,
         bp                TYPE string,
         sp_gl_ind         TYPE string,
         amt_doccur        TYPE string,
*         amt_base          TYPE string,
         tax_code          TYPE string,
         tax_amt           TYPE string,
         businessplace     TYPE string,
         segment           TYPE string,
         costcenter        TYPE string,
         profit_ctr        TYPE string,
         item_text         TYPE string,
         alloc_nmbr        TYPE string,
         pmnttrms          TYPE string,
         bline_date        TYPE string,
         pmnt_block        TYPE string,
         pymt_meth         TYPE string,
         partner_bk        TYPE string,
         neg_postng        TYPE string,
         ref_key_1         TYPE string,
         ref_key_2         TYPE string,
         ref_key_3         TYPE string,
         name_1            TYPE string,
         street            TYPE string,
         city              TYPE string,
         tax_no_1          TYPE char16,
         period            TYPE string, "add thanhnt 04.02.2023
         kokrs             TYPE string,
         kndnr             TYPE string,
         artnr             TYPE string,
         fkart             TYPE string,
         kdpos             TYPE string,
         kaufn             TYPE string,
         werks             TYPE string,
         fkber             TYPE string,
         vkorg             TYPE string,
         vtweg             TYPE string,
         spart             TYPE string,
         pspnr             TYPE string,
         kstrg             TYPE string,
         pprctr            TYPE string,
         kmvkrg            TYPE string,
         kmvtnr            TYPE string,
         kunre             TYPE string,
         kunwe             TYPE string,
         wwpgr             TYPE string,
         kmvkbu            TYPE string,
         wwser             TYPE string,
         wwlv              TYPE string,
         zrefkey4          TYPE string,
         per_offstng_accnt TYPE string,
         life_start_date   TYPE string,
         life_end_date     TYPE string,
         acrobj_id         TYPE string,
       END OF ty_upload.

TYPES: BEGIN OF  ty_upload_post,
         stt               TYPE string,
         doc_date          TYPE string,
         pstng_date        TYPE string,
         header_txt        TYPE string,
         mau_hd            TYPE string,
         ref_doc_no        TYPE string,
         doc_type          TYPE string,
         comp_code         TYPE string,
         currency          TYPE string,
         trans_date        TYPE string,
         xref1_hd          TYPE string,
         xref2_hd          TYPE string,
         de_cre_ind1       TYPE string,
         gl_account        TYPE string,
*         CUSTOMER    TYPE STRING,
*         VENDOR_NO   TYPE STRING,
         bp                TYPE string,
         sp_gl_ind         TYPE string,
         amt_doccur        TYPE string,
*         amt_base          TYPE string,
         tax_code          TYPE string,
         tax_amt           TYPE string,
         businessplace     TYPE string,
         segment           TYPE string,
         costcenter        TYPE string,
         profit_ctr        TYPE string,
         item_text         TYPE string,
         alloc_nmbr        TYPE string,
         pmnttrms          TYPE string,
         bline_date        TYPE string,
         pmnt_block        TYPE string,
         pymt_meth         TYPE string,
         partner_bk        TYPE string,
         neg_postng        TYPE string,
         ref_key_1         TYPE string,
         ref_key_2         TYPE string,
         ref_key_3         TYPE string,
         name_1            TYPE string,
         street            TYPE string,
         city              TYPE string,
         tax_no_1          TYPE char16,
         period            TYPE string,
         kokrs             TYPE string,
         kndnr             TYPE string,
         artnr             TYPE string,
         fkart             TYPE string,
         kdpos             TYPE string,
         kaufn             TYPE string,
         werks             TYPE string,
         fkber             TYPE string,
         vkorg             TYPE string,
         vtweg             TYPE string,
         spart             TYPE string,
         pspnr             TYPE string,
         kstrg             TYPE string,
         pprctr            TYPE string,
         kmvkrg            TYPE string,
         kmvtnr            TYPE string,
         kunre             TYPE string,
         kunwe             TYPE string,
         wwpgr             TYPE string,
         kmvkbu            TYPE string,
         wwser             TYPE string,
         wwlv              TYPE string,
         zrefkey4          TYPE string,
         per_offstng_accnt TYPE string,
         life_start_date   TYPE string,
         life_end_date     TYPE string,
         acrobj_id         TYPE string,
       END OF ty_upload_post.

TYPES: BEGIN OF  ty_data,
         stt               TYPE i,
         doc_date          TYPE budat,
         pstng_date        TYPE budat,
         header_txt        TYPE char25,
         mau_hd            TYPE char20,
         ref_doc_no        TYPE char16,
         doc_type          TYPE char2,
         comp_code         TYPE bukrs,
         currency          TYPE waers,
         trans_date        TYPE budat,
         xref1_hd          TYPE char20,
         xref2_hd          TYPE char20,
         de_cre_ind1       TYPE char1,
         gl_account        TYPE hkont,
         customer          TYPE char10,
         vendor_no         TYPE char10,
         bp                TYPE char10,
         sp_gl_ind         TYPE char1,
         amt_doccur        TYPE bapidoccur,
*         amt_base          TYPE bapiamtbase,
         tax_code          TYPE char2,
         tax_amt           TYPE bapitaxamt,
         businessplace     TYPE char4,
         segment           TYPE char10,
         costcenter        TYPE char10,
         profit_ctr        TYPE char10,
         item_text         TYPE string,
         alloc_nmbr        TYPE char18,
         pmnttrms          TYPE char10,
         bline_date        TYPE budat,
         pmnt_block        TYPE char1,
         pymt_meth         TYPE char1,
         partner_bk        TYPE char4,
         neg_postng        TYPE char1,
         ref_key_1         TYPE char12,
         ref_key_2         TYPE char50,
         ref_key_3         TYPE char20,
         name_1            TYPE char140,
         street            TYPE char35,
         city              TYPE char35,
         tax_no_1          TYPE char16,
         kokrs             TYPE char4,
         kndnr             TYPE char10,
         artnr             TYPE char40,
         fkart             TYPE char4,
         kdpos             TYPE kdpos,
         kaufn             TYPE char10,
         werks             TYPE werks,
         fkber             TYPE fkber,
         vkorg             TYPE vkorg,
         vtweg             TYPE vtweg,
         spart             TYPE spart,
         pspnr             TYPE ps_psp_pnr,
         kstrg             TYPE kstrg,
         pprctr            TYPE pprctr,
         kmvkrg            TYPE vkgrp,
         kmvtnr            TYPE vrtnr,
         kunre             TYPE kunre,
         kunwe             TYPE kunwe,
         wwpgr             TYPE rkeg_wwpgr,
         kmvkbu            TYPE vkbur,
         wwser             TYPE rkeg_wwser,
         wwlv              TYPE rkeg_wwlv,
         zrefkey4          TYPE zdt_refkey4,
         per_offstng_accnt TYPE ace_accnt_periodic_offsetting,
         life_start_date   TYPE ace_life_start_date,
         life_end_date     TYPE ace_life_end_date,
         acrobj_id         TYPE acr_obj_id,
         period            TYPE monat,
       END OF ty_data.

TYPES: BEGIN OF  ty_mess,
         status        TYPE icons-text,
         message       TYPE char255,
         belnr         TYPE belnr_d,
         doc_date      TYPE budat,
         pstng_date    TYPE budat,
         header_txt    TYPE char25,
         mau_hd        TYPE char20,
         ref_doc_no    TYPE char16,
         doc_type      TYPE char2,
         comp_code     TYPE bukrs,
         currency      TYPE waers,
         trans_date    TYPE budat,
         xref1_hd      TYPE char20,
         xref2_hd      TYPE char20,
         de_cre_ind1   TYPE char1,
         gl_account    TYPE hkont,
         customer      TYPE char10,
         vendor_no     TYPE char10,
         bp            TYPE char10,
         sp_gl_ind     TYPE char1,
         amt_doccur    TYPE char255,
*         amt_base      TYPE char255,
         tax_code      TYPE string,
         tax_amt       TYPE bapitaxamt,
         businessplace TYPE char4,
         segment       TYPE char10,
         costcenter    TYPE char10,
         profit_ctr    TYPE char10,
         item_text     TYPE string,
         alloc_nmbr    TYPE char18,
         pmnttrms      TYPE char10,
         bline_date    TYPE budat,
         pmnt_block    TYPE char1,
         pymt_meth     TYPE char1,
         partner_bk    TYPE char4,
         neg_postng    TYPE char1,
         ref_key_1     TYPE char12,
         ref_key_2     TYPE char12,
         ref_key_3     TYPE char20,
         name_1        TYPE char140,
         street        TYPE char35,
         city          TYPE char35,
         tax_no_1      TYPE char16,
         kokrs         TYPE char4,
         kndnr         TYPE char10,
         artnr         TYPE char40,
         fkart         TYPE char4,
         kdpos         TYPE kdpos,
         kaufn         TYPE char10,
         werks         TYPE werks,
         fkber         TYPE fkber,
         vkorg         TYPE vkorg,
         vtweg         TYPE vtweg,
         spart         TYPE spart,
         pspnr         TYPE ps_psp_pnr,
         kstrg         TYPE kstrg,
         pprctr        TYPE pprctr,
         kmvkrg        TYPE vkgrp,
         kmvtnr        TYPE vrtnr,
         kunre         TYPE kunre,
         kunwe         TYPE kunwe,
         wwpgr         TYPE rkeg_wwpgr,
         kmvkbu        TYPE vkbur,
         wwser         TYPE rkeg_wwser,
         wwlv          TYPE rkeg_wwlv,
         line          TYPE i,
         status2       TYPE icons-text,
       END OF ty_mess.
TYPES: gty_t_bdcdata TYPE TABLE OF bdcdata.
DATA: gt_upload TYPE TABLE OF ty_upload_post.
DATA: gt_upload2 TYPE TABLE OF ty_upload.
*DATA: GT_UPLOAD2 TYPE TABLE OF TY_UPLOAD2.
DATA: gt_data TYPE TABLE OF ty_data.
DATA: gt_message TYPE TABLE OF ty_mess.
DATA: gw_check TYPE i.
DATA: gw_fname TYPE filename75.
DATA: gw_check_post TYPE boolean.
DATA: gt_alv      TYPE STANDARD TABLE OF ty_mess,
      gs_alv      TYPE ty_mess,
      gt_fieldcat TYPE STANDARD TABLE OF lvc_s_fcat,
      ob_cont     TYPE REF TO cl_gui_custom_container,
      ob_grd      TYPE REF TO cl_gui_alv_grid.
DATA: gr_type_pgr_up TYPE fccx_t_range_row,
      gr_acc_pgr_up  TYPE fccx_t_range_row,
      gt_partner_gr  TYPE TABLE OF ztb_partner_gr.
DATA: gw_form_name TYPE lvc_fname.
DATA: gt_t012k TYPE TABLE OF t012k.
DATA: gt_t042i TYPE TABLE OF t042i.
DATA: gt_t001 TYPE TABLE OF t001.
DATA: gt_but000 TYPE TABLE OF but000.
DATA: gt_cepc TYPE TABLE OF cepc.
DATA: gt_cepc_cc TYPE TABLE OF cepc.
DATA: gt_csks TYPE TABLE OF csks.
DATA: gt_a003 TYPE TABLE OF a003.
DATA: gt_bplace TYPE TABLE OF j_1bbranch.
DATA: gt_fagl_segm TYPE TABLE OF fagl_segm.
DATA: gt_seg TYPE TABLE OF fagl_segm.
DATA: gt_skb1 TYPE TABLE OF skb1.
DATA: gt_skb1_aut TYPE TABLE OF skb1.
DATA: gt_tbsl TYPE TABLE OF tbsl.
DATA: gt_bank TYPE TABLE OF fclm_bam_amd.
DATA: gt_t003 TYPE TABLE OF t003.
DATA: gt_bseg TYPE TABLE OF bseg."add by HUNGVT

SELECTION-SCREEN BEGIN OF BLOCK a1 WITH FRAME TITLE TEXT-001.
PARAMETERS: p_file LIKE rlgrap-filename MODIF ID a.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(31) TEXT-002.
PARAMETERS p_test AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(31) TEXT-007.
PARAMETERS p_ctgs AS CHECKBOX DEFAULT ''."add by HUNGVT
SELECTION-SCREEN END OF LINE.
PARAMETERS p_ptax TYPE char1 NO-DISPLAY.
*SELECTION-SCREEN BEGIN OF LINE.
*SELECTION-SCREEN COMMENT 1(31) TEXT-008.
*PARAMETERS p_ptax AS CHECKBOX DEFAULT ''."add by VINHNQ
*SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK a1.

SELECTION-SCREEN FUNCTION KEY 1.
